//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demoEntities : DbContext
    {
        public demoEntities()
            : base("name=demoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material_type_import> Material_type_import { get; set; }
        public DbSet<Partner_products_import> Partner_products_import { get; set; }
        public DbSet<Partner_type> Partner_type { get; set; }
        public DbSet<Partners_import> Partners_import { get; set; }
        public DbSet<Product_type_import> Product_type_import { get; set; }
        public DbSet<Products_import> Products_import { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
