//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners_import
    {
        public Partners_import()
        {
            this.Partner_products_import = new HashSet<Partner_products_import>();
        }
    
        public byte id { get; set; }
        public byte partner_type_id { get; set; }
        public string partner { get; set; }
        public string director { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public long inn { get; set; }
        public byte rating { get; set; }
        public int new_id { get; set; }
    
        public virtual ICollection<Partner_products_import> Partner_products_import { get; set; }
    }
}
