//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products_import
    {
        public byte id { get; set; }
        public byte production_id { get; set; }
        public byte partner_id { get; set; }
        public int prod_ammount { get; set; }
        public System.DateTime sale_date { get; set; }
    
        public virtual Partners_import Partners_import { get; set; }
        public virtual Products_import Products_import { get; set; }
    }
}
