//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_import
    {
        public Products_import()
        {
            this.Partner_products_import = new HashSet<Partner_products_import>();
        }
    
        public byte id { get; set; }
        public byte prod_type_id { get; set; }
        public string production { get; set; }
        public int article { get; set; }
        public decimal min_price_for_partner { get; set; }
    
        public virtual ICollection<Partner_products_import> Partner_products_import { get; set; }
        public virtual Product_type_import Product_type_import { get; set; }
    }
}
